[package]
name = "aoc_rust_2022_3"
version = "1.0.0"
authors = ["https://github.com/Garcel"]
edition = "2021"

[dependencies]
itertools = "0.10.5"

[[bench]]
name = "bench"
path = "src/bench.rs"
harness = false
